version: '3.7'
services:
  app:
    build: ./app
    restart: always
    working_dir: /var/www/html
    command: bash -c "cron && service supervisor stop && service supervisor start && supervisorctl start laravel-worker:* && apache2-foreground"
    volumes:
      - ./app/php.ini:/etc/php/7.2/apache2/php.ini
    ports:
      - ${APP_HTTP_PORT}:80
      - ${APP_HTTPS_PORT}:443
  postgres:
    image: postgres:9.6
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./postgres/.env
  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    ports:
      - ${PGADMIN4_PORT}:80
    env_file:
      - ./pgadmin4/.env
volumes:
  postgres-data: